title:        Gravityblast
tagline:      "by Andrea Franz"
url:          http://gravityblast.com
author:
  name:       "Andrea Franz"
  email:      "andrea@gravityblast.com"
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
